import Button from './components/Button/Button';
import ButtonGroup from './components/ButtonGroup/ButtonGroup';
import Card from './components/Card/Card';
import Container from './components/Container/Container';
import DateTime from './components/DateTime/DateTime';
import Dialog from './components/Dialog/Dialog';
import Dropdown from './components/Dropdown/Dropdown';
import Form from './components/Form/Form';
import Grid from './components/Grid/Grid';
import Icon from './components/Icon/Icon';
import Link from './components/Link/Link';
import Navigation from './components/Navigation/Navigation';
import Strip from './components/Strip/Strip';
import Tab from './components/Tab/Tab';
import TabGroup from './components/TabGroup/TabGroup';
import HeroBanner from './modules/HeroBanner/HeroBanner';
import './styles/main.css';

declare const lib: {
    Button: typeof Button;
    ButtonGroup: typeof ButtonGroup;
    Card: typeof Card;
    Container: typeof Container;
    DateTime: typeof DateTime;
    Dialog: typeof Dialog;
    Dropdown: typeof Dropdown;
    Form: typeof Form;
    Grid: typeof Grid;
    Icon: typeof Icon;
    Link: typeof Link;
    Navigation: typeof Navigation;
    Strip: typeof Strip;
    Tab: typeof Tab;
    TabGroup: typeof TabGroup;
    HeroBanner: typeof HeroBanner;
};
export default lib;
